// <auto-generated />
using System;
using FamilyBudget.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyBudget.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20230131191110_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FamilyBudget.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("RepeatDay")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Salary",
                            CreatedTime = new DateTime(2022, 12, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5122),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5125),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = 821m
                        },
                        new
                        {
                            Id = 2,
                            Category = "General",
                            CreatedTime = new DateTime(2022, 12, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5136),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5138),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = -163m
                        },
                        new
                        {
                            Id = 3,
                            Category = "MonthlyRepetition",
                            CreatedTime = new DateTime(2022, 12, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5142),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5144),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = -55m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Salary",
                            CreatedTime = new DateTime(2022, 11, 30, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5148),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5150),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = 524m
                        },
                        new
                        {
                            Id = 5,
                            Category = "General",
                            CreatedTime = new DateTime(2022, 11, 30, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5153),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5155),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = -459m
                        },
                        new
                        {
                            Id = 6,
                            Category = "MonthlyRepetition",
                            CreatedTime = new DateTime(2022, 11, 30, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5159),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5161),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = -55m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Salary",
                            CreatedTime = new DateTime(2022, 10, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5163),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5165),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = 696m
                        },
                        new
                        {
                            Id = 8,
                            Category = "General",
                            CreatedTime = new DateTime(2022, 10, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5168),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5170),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = -668m
                        },
                        new
                        {
                            Id = 9,
                            Category = "MonthlyRepetition",
                            CreatedTime = new DateTime(2022, 10, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5172),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5174),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = -55m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Salary",
                            CreatedTime = new DateTime(2022, 9, 30, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5177),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5179),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = 736m
                        },
                        new
                        {
                            Id = 11,
                            Category = "General",
                            CreatedTime = new DateTime(2022, 9, 30, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5182),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5184),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = -886m
                        },
                        new
                        {
                            Id = 12,
                            Category = "MonthlyRepetition",
                            CreatedTime = new DateTime(2022, 9, 30, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5186),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5188),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = -55m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Salary",
                            CreatedTime = new DateTime(2022, 8, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5191),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5193),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = 449m
                        },
                        new
                        {
                            Id = 14,
                            Category = "General",
                            CreatedTime = new DateTime(2022, 8, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5195),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5197),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = -303m
                        },
                        new
                        {
                            Id = 15,
                            Category = "MonthlyRepetition",
                            CreatedTime = new DateTime(2022, 8, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5200),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5202),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = -55m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Salary",
                            CreatedTime = new DateTime(2022, 7, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5204),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5206),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = 512m
                        },
                        new
                        {
                            Id = 17,
                            Category = "General",
                            CreatedTime = new DateTime(2022, 7, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5208),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5210),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = -303m
                        },
                        new
                        {
                            Id = 18,
                            Category = "MonthlyRepetition",
                            CreatedTime = new DateTime(2022, 7, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5213),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5215),
                            OwnerId = 1,
                            RepeatDay = 0,
                            Value = -55m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Health",
                            CreatedTime = new DateTime(2023, 5, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5218),
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since",
                            ModifiedTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5220),
                            OwnerId = 1,
                            RepeatDay = 14,
                            Value = -55m
                        });
                });

            modelBuilder.Entity("FamilyBudget.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Sex")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "A@1",
                            Name = "Aygyun",
                            Password = "Fitness124",
                            RegisteredTime = new DateTime(2023, 1, 31, 21, 11, 9, 971, DateTimeKind.Local).AddTicks(5057),
                            Sex = true
                        });
                });

            modelBuilder.Entity("FamilyBudget.Entities.Transaction", b =>
                {
                    b.HasOne("FamilyBudget.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
